# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Update all crate versions together
consolidate-commits = true
# Automatically push to remote
push = false
# Automatically create git tags
tag = true
# Tag name prefix
tag-prefix = "v"
# Tag message template
tag-message = "Release version {{version}}"
# Don't publish automatically (we'll do it manually)
publish = false
