# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Update all crate versions together
consolidate-commits = true
# Automatically push to remote
push = false
# Automatically create git tags
tag = true
# Tag message template
tag-message = "Release version {{version}}"
# Don't publish automatically (we'll do it manually)
publish = false

# Note: cargo-release adds 'v' prefix by default, so no need to set tag-prefix
